[package]
name = "ralloc"
version = "0.1.0"
authors = ["ticki <ticki@users.noreply.github.com>"]

[dependencies.extra]
git = "https://github.com/redox-os/libextra.git"

[target.'cfg(unix)'.dependencies]
syscall = "0.2.1"
