[package]
name = "ralloc"
version = "1.0.0"
authors = ["ticki <ticki@users.noreply.github.com>"]

# URLs and paths
description = "An efficient alternative platform-agnostic allocator."
repository = "https://github.com/redox-os/ralloc"
readme = "README.md"

# Metadata
keywords = ["alloc", "malloc", "allocator", "ralloc", "redox"]
license = "MIT"

[dependencies.ralloc_shim]
path = "shim"

[dependencies.clippy]
version = "0.0.80"
optional = true

[dependencies.unborrow]
git = "https://github.com/durka/unborrow.git"

[profile.release]
panic = "abort"
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[features]
default = ["allocator", "clippy"]
# ---
alloc_id = []
allocator = []
debug_tools = []
libc_write = []
log = ["libc_write", "alloc_id"]
security = []
testing = ["log", "libc_write", "debug_tools"]
unsafe_no_brk_lock = []
unsafe_no_mutex_lock = []
